encoding:       utf-8
markdown:       redcarpet
exclude:        scripts tmp templates README.mkd
permalink:      pretty

redcarpet:
  extensions: [ 'autolink', 'tables' ]

base-url: http://documentation.kii.com/

external-keys:
  google:       '011947291164067706467:czagiboexqa'
  disqus:       'kiidoc'

flags:
  sidebar-autoscroll: true
  robots-disallow-all: false
  google-analytics: true

# vim:set ts=8 sts=2 sw=2 tw=0 et:
