encoding:       utf-8
markdown:       redcarpet
exclude:        scripts tmp templates README.mkd
permalink:      pretty

redcarpet:
  extensions: [ 'autolink', 'hard_wrap', 'tables' ]

base-url: http://documentation.kii.com/

# vim:set ts=8 sts=2 sw=2 tw=0 et:
